### ISSUE TITLE
DNS lookups for domains using Cloudflare NS only returns A records

### ISSUE THREAD

**Issue by iglvzx** [iglvzx/gwhois.org#3]
![2016-12-08 10_18_34-cloudflare com - dns - gwhois org](https://cloud.githubusercontent.com/assets/981885/21021978/c7ca6a92-bd2f-11e6-98b3-94b529a03b2a.png)

**Comment by iglvzx** [comment]
Cloudflare's name servers implement the `dnsop-refuse-any` standard and refuse lookups asking for `ANY` record type.

Current behavior is to catch this response and then do an `A` record lookup, which is why you only see the A records instead of seeing the `dnsop-refuse-any` response.

**Comment by fm** [comment]
CloudFlare-hosted domains seem to not return anything anymore...

**Comment by iglvzx** [comment]
Fixed the parsing/handling of `dnsop-refuse-any` DNS responses to be more flexible.

![2017-08-29_16-13-11](https://user-images.githubusercontent.com/981885/29848391-1db5e09c-8cd5-11e7-869e-619388407e26.png)

**Comment by alento-group** [comment]
Cloudflare hosted domains are now not returning anything but 


Hostname | TTL | Type | Value
-- | -- | -- | --
parallaxmedia.io. | 3789 | HINFO | "RFC8482" ""

as an example, see https://gwhois.org/parallaxmedia.io+dns

Can you adjust this behaviour?  Or is Cloudflare just sh!t?

**Comment by myfirstnameispaul** [comment]
@alento-group 

Issues related to RFC8482 are not related to the original A record issue reported by OP.

I have just opened issue #29 for RFC8482.

It may be the case that this issue (#3) can be closed as it is likely no longer relevant.

**Comment by myfirstnameispaul** [comment]
On second thought, it may be possible that these issues are indirectly related, only in that Cloudflare has been working on eliminating the ANY query responses for some time.

https://blog.cloudflare.com/deprecating-dns-any-meta-query-type/

> If you are aware of any software that relies solely on ANY queries, now is the time to fix it.
