### ISSUE TITLE
Cannot do lookups on domains with underscores

### ISSUE THREAD

**Issue by fm** [iglvzx/gwhois.org#31]
If you do a lookup for a domain with an underscore (eg: DMARC records) the app gives an error and does not process the lookup "_Invalid domain name / IP address format_."

Eg: _dmarc.domain.com

**Comment by iglvzx** [comment]
This is expected on the Whois (main) tool.

For querying for DNS records, use the DNS tool: https://gwhois.org/dns/

Example:

https://gwhois.org/dns/_dmarc.domain.com

![image](https://user-images.githubusercontent.com/981885/167227670-ce24f118-06ff-4ae3-84a3-1d9e15d1d51c.png)
