### ISSUE TITLE
Cannot lookup the registry and registrar whois server

### ISSUE THREAD

**Issue by zenotiger** [iglvzx/gwhois.org#32]
Cannot lookup the registry and registrar whois server

**Comment by zipzit** [comment]
yup, me too, for ANY URL, even those I own.

> Could not connect to whois.iana.org.
To view known issues or report a new issue, please visit: https://github.com/iglvzx/gwhois.org/issues

**Comment by iglvzx** [comment]
whois.iana.org was having issues this day. Closing this issue as it is old.
