### ISSUE TITLE
Porkbun name servers return no results

### ISSUE THREAD

**Issue by AnyDomainLLC** [iglvzx/gwhois.org#35]
Domains which are served by Porkbun name servers return the following message:

No DNS records found

I have checked several domains registered at Porkbun using their name servers.

**Comment by iglvzx** [comment]
Hello.

Thanks for pointing this out!

It looks like Porkbun name servers do not refuse `ANY` queries per https://datatracker.ietf.org/doc/html/rfc8482 (i.e. the way CloudFlare refuses these queries).

So, as a best effort, I updated GWhois.org to direct the user to try with a different record type when this situation is encountered for any name servers. Similar to the update in https://github.com/iglvzx/gwhois.org/issues/29

![image](https://user-images.githubusercontent.com/981885/167166771-24ebc67d-450b-4910-ba3d-c1f5ae334da2.png)

![image](https://user-images.githubusercontent.com/981885/167166506-171ad90d-87c7-4821-91e1-432ac400d86b.png)

**Comment by AnyDomainLLC** [comment]
Awesome!  Issue #29 is closed, so I am not certain that you will see my comments there,  Please check them, thanks!
