### ISSUE TITLE
Strange Log Entries

### ISSUE THREAD

**Issue by alento-group** [iglvzx/gwhois.org#36]
Produced this log on the mail server:
```
2022-07-06 21:45:11 SMTP connection from [34.218.196.242]:40028 (TCP/IP connection count = 12)
2022-07-06 21:45:11 H=gwhois.org [34.218.196.242]:40028 Warning: redacted
2022-07-06 21:45:12 unexpected disconnection while reading SMTP command from gwhois.org [34.218.196.242]:40028 D=0s
```

But what is really concerning is what the heck are the other three user email accounts doing there?  They were NOT a part of the input ...  I searched for `redacted`

**Comment by iglvzx** [comment]
The output shown on GWhois.org are the exact steps taken.

i.e.

1. Open TCP connection to `$ipAddress` on port 25
   1. Send `helo gwhois.org`
   1. Record response
   1. Send `mail from: <mail@gwhois.org>`
   1. Record response
   1. Send `rcpt to: <$emailAddress>`
   1. Record response
1. Close connection

This can be replicated using `telnet` or some other tool to send the same kind of commands to the mail server.

Suggest checking your mail server configuration to identify why those additional email addresses appear in the mail server logs.

**Comment by alento-group** [comment]
_Suggest checking your mail server configuration to identify why those additional email addresses appear in the mail server logs._

It appears because you sent the data ...

**Comment by mxroute** [comment]
So, apparently, I've never witnessed a situation where a connection was closed after RCPT TO where aliases existed, with exim. One would think it might be something I'd seen before, but it wasn't. Apparently exim logs the aliases in this way, when this exact scenario occurs.

**Comment by alento-group** [comment]
Hmm, ok then @mxroute your explanation makes sense.  The data is just being logged by exim ... not being sent by gwhois.org nor being returned to them.

Good to know, thanks all.
