### ISSUE TITLE
DNS section is not shown for .org domains

### ISSUE THREAD

**Issue by MVS** [iglvzx/gwhois.org#4]
A whois lookup for a .com domain shows 5 sections at the bottom level: status, the 3 contacts, and DNS.  For example: https://gwhois.org/google.com

However, on a .org domain, only 4 sections are shown (the DNS section is missing).  To see the nameservers, you need to switch to the raw view.  For example: https://gwhois.org/google.org

**Comment by MVS** [comment]
This issue also affects other registries operated by PIR:
https://gwhois.org/nic.ngo
https://gwhois.org/nic.ong

**Comment by iglvzx** [comment]
Fixed. Updated the parsing algorithm for PIR whois data so the DNS section (and name servers) are parsed correctly again.

![2016-12-12 18_45_09-google com - gwhois org](https://cloud.githubusercontent.com/assets/981885/21125524/32912686-c09b-11e6-9aed-10df49947330.png)

**Comment by iglvzx** [comment]
![2016-12-12 18_48_10-google org - gwhois org](https://cloud.githubusercontent.com/assets/981885/21125570/9633d08a-c09b-11e6-9fc8-136edbb6be2e.png)
